---
# file: main.yml

- hosts: 127.0.0.1
  connection: local

  vars_files:
  - "roles/vikashkothary.dotfiles/vars/main.yml"
  - "roles/vikashkothary.dotfiles/defaults/main.yml"
  - "roles/vikashkothary.programs/vars/main.yml"
  - "roles/vikashkothary.programs/defaults/main.yml"

  tasks:
    - include: "roles/vikashkothary.dotfiles/tasks/uninstall.yml"
      tags: ["uninstall"]
    - include: "roles/vikashkothary.dotfiles/tasks/install.yml"
      tags: ["install"]
    - include: "roles/vikashkothary.programs/tasks/uninstall.yml"
      tags: ["uninstall"]
    - include: "roles/vikashkothary.programs/tasks/install.yml"
      tags: ["install"]

  tasks:
  - include_tasks: tasks/uninstall.yml
    tags: ["uninstall"]
  - include_tasks: tasks/install.yml
    tags: ["install"]

  # roles:
  #   - role: vikashkothary.dotfiles

  tasks: