---
# file: main.yml

- hosts: localhost

  vars_files:
  - "roles/vikashkothary.dotfiles/vars/main.yml"
  - "roles/vikashkothary.dotfiles/defaults/main.yml"
  - "roles/vikashkothary.programs/vars/main.yml"
  - "roles/vikashkothary.programs/defaults/main.yml"

  tasks:
  - include: tasks/uninstall.yml
    tags: ["uninstall"]
  - include: tasks/install.yml
    tags: ["install"]