---
# file: provision.yml

- hosts: localhost
  tasks:
  - name: Add apt key
    apt_key: url={{item}} state=present
    with_items:
    - https://download.sublimetext.com/sublimehq-pub.gpg
    become: true

  - name: Add PPA repositories
    apt_repository: repo='{{item}}'
    with_items:
    - 'ppa:gnome-terminator' 
    - 'ppa:jonathonf/vim'
    - 'ppa:deluge-team/ppa'
    - 'ppa:team-xbmc/ppa'
    - 'deb https://download.sublimetext.com/ apt/stable/'
    - 'ppa:mozillateam/firefox-next'
    - 'ppa:danielrichter2007/grub-customizer'
    become: true

  - name: Install apt packages
    apt:
      pkg:
      - apt-transport-https
      - linux-headers-generic
      - ca-certificates
      - curl
      - software-properties-common
      - blueman
      - pulseaudio-module-bluetooth 
      - grub-customizer
      - compiz
      - compizconfig-settings-manager
      - compiz-plugins
      - preload
      - thefuck
      - terminator
      - vim
      - tmux
      - deluge
      - sublime-text
      - trash-cli
      - gparted
      - git
      - redshift-gtk
      - kodi
      - kodi-peripheral-joystick
      - virtualbox
      - virtualbox-dkms
      - vagrant
      - inotify-tools
      - ntfs-3g
      - unrar
      - firefox
      state: present
      update_cache: false
    become: true

  - name: Download packages
    get_url:
      url: '{{ item.url }}'
      dest: '/tmp/{{ item.name }}'
    with_items:
    - { name: 'android-studio.zip', url: 'https://dl.google.com/dl/android/studio/ide-zips/3.1.3.0/android-studio-ide-173.4819257-linux.zip' }
    - { name: 'google-chrome.deb', url: 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb' }
    - { name: 'gitkraken.deb', url: 'https://release.gitkraken.com/linux/gitkraken-amd64.deb' }
    - { name: 'anki.tar.bz2', url: 'https://apps.ankiweb.net/downloads/current/anki-2.0.52-amd64.tar.bz2' }
    - { name: 'synergy.deb', url: 'https://github.com/brahma-dev/synergy-stable-builds/releases/download/v1.8.8-stable/synergy-v1.8.8-stable-Linux-x86_64.deb' }
    - { name: 'jenkins.war', url: 'http://mirrors.jenkins.io/war-stable/latest/jenkins.war' }
    - { name: 'skype.deb', url: 'https://repo.skype.com/latest/skypeforlinux-64.deb' }

  - name: Install deb packages
    apt: deb='/tmp/{{ item }}.deb'
    with_items:
    - google-chrome
    - gitkraken
    - skype
    become: true
  
  - name: Install zip packages
    unarchive:
      src: /tmp/{{ item }}.zip
      dest: /opt
    with_items:
    - android-studio
    become: true

  - name: Install snap packages
    command: snap install {{item}}
    with_items:
    - intellij-idea-community --classic --edge
    become: true

  #- name: Install war packages
  #  command: java -jar {{ item }}.war
  #  with_items:
  #  - jenkins

  - name: Create directories
    file:
      path: '{{ item }}'
      state: directory
      recurse: yes
    with_items:
    - '/home/vikash/.config/terminator/'
    - '/home/vikash/.local/share/applications/'

  - name: Move files
    file:
      src: '{{ playbook_dir }}/files/{{ item.file }}'
      dest: '{{ item.dest }}'
      state: link
      force: true
    with_items:
    - { file: 'dotfiles/vimrc', dest: '/home/vikash/.vimrc' }
    - { file: 'dotfiles/tmux.conf', dest: '/home/vikash/.tmux.conf' }
    - { file: 'dotfiles/bashrc', dest: '/home/vikash/.bashrc' }
    - { file: 'dotfiles/bash-aliases', dest: '/home/vikash/.bash_aliases' }
    - { file: 'dotfiles/gitconfig', dest: '/home/vikash/.gitconfig' }
    - { file: 'terminator-config', dest: '/home/vikash/.config/terminator/config' }
    - { file: 'androidstudio.desktop', dest: '/home/vikash/.local/share/applications/androidstudio.desktop' }

#  - name: Run scripts
#    command: 'sh {{ playbook_dir }}/scripts/{{ item }}.sh'
#    with_items:
#    - auto-clean

# - name: Latest LTS
#   command: /usr/lib/ubuntu-release-upgrader/check-new-release-gtk
