---
# file: install.yml

- name: create installation configuration file
  file:
    path: ~/Desktop/setup.txt
    state: touch

- name: install dotfiles
  include: "../roles/vikashkothary.dotfiles/tasks/install.yml"