---
# file: main.yml

- hosts: all
  connection: local

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: vikashkothary.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]

  tasks:
  - include_tasks: tasks/install.yml


