---
# file: uninstall.yml

- name: remove installation configuration file
  file:
    path: ~/Desktop/setup.txt
    state: absent

- name: uninstall dotfiles
  include: "roles/vikashkothary.dotfiles/tasks/uninstall.yml"